// Code generated by goctl. DO NOT EDIT.
package types

type PingReq struct {
}

type PingRes struct {
	Message string `json:"message"`
	Time    string `json:"time"`
}

type UserInfoReq struct {
}

type UserInfoRes struct {
	UUID     string `json:"uuid"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
}
