// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "nav-go-zero/app/nav-web/api/internal/handler/auth"
	"nav-go-zero/app/nav-web/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: pingHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/user/info",
				Handler: userInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/auth/getToken",
				Handler: auth.GetTokenHandler(serverCtx),
			},
		},
	)
}
