global:
  scrape_interval:
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  #global catch time
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'web.api'
    static_configs:
      - targets: [ '192.168.31.214:11011' ]
        labels:
          job: web.api
          app: web.api
          env: dev
  - job_name: 'user.rpc'
    static_configs:
      - targets: [ '192.168.31.214:11111' ]
        labels:
          job: user.rpc
          app: user.rpc
          env: dev
